### ISSUE TITLE
bug(steps): handle col with one unique value in Scale* step

### ISSUE THREAD

**Issue by jitingxu1** [ibis-project/ibis-ml#119]
similar issue to #118 

When scaling, we need to calculate the min and max for ScaleMinMax, or the standard deviation for ScaleStandard.

If a column has only one unique value, the standard deviation (std) will be 0, or max - min will be 0.

This will result in the entire column being transformed to None.

**Comment by deepyaman** [comment]
Sounds like something we should fix. :)
