### ISSUE TITLE
bug(steps): remove set_categories in ExpandDate/Time steps

### ISSUE THREAD

**Issue by jitingxu1** [ibis-project/ibis-ml#123]
In the provided code snippet [here](https://github.com/ibis-project/ibis-ml/blob/main/ibis_ml/steps/_temporal.py#L84), month and dow are set as category variables. However, their actual type is numeric. This can potentially impact downstream transformations, particularly in selectors. For instance, if `birth_date_dow` is stored as an integer but categorized in metadata as a category variable, it might not be selectable for subsequent preprocessing steps.

**Comment by jcrist** [comment]
This was intentional since these values are categorical in nature and shouldn't be treated as numeric. We want to avoid a `numeric` selector operation from e.g. applying normalization to these columns, since they're not really numeric. This also matches what `tidymodels` does. Do you have reason we should treat these as numeric?

**Comment by jitingxu1** [comment]
I do not have a strong stand if we should treat them as numeric or categorical columns. Since they are converted to ordered values, I believe it is OK to treat them as numeric value, if we want to do OrdinalEncode.  

Another reason is that, when we do the imputing, we need a special way to select these columns, since the data type is `INT` but marked as categorical in metadata.  Some common selectors like `ml.numeric()` or `ml.string()` cannot capture them, we may need to pass the exact name for preprocessing these kind of columns.  Not sure if there is other good way to select these columns.

**Comment by deepyaman** [comment]
Can you check if `ml.categorical()` works?

**Comment by jitingxu1** [comment]
> Can you check if `ml.categorical()` works?

my bad, sounds great. I will try and close this issue.

**Comment by jitingxu1** [comment]
I could use `ml.categorical()`, close it.
