### ISSUE TITLE
ibis_ml has no attribute datetime

### ISSUE THREAD

**Issue by koaning** [ibis-project/ibis-ml#134]
There are a few places on the docs that refer to a datetime selector (like [here](https://ibis-project.github.io/ibis-ml/reference/steps-temporal-feature-extraction.html#examples)). 

```python
import ibis_ml as iml

iml.datetime()
```

However, it seems that this does not exist. 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[17], line 3
      1 import ibis_ml as iml
----> 3 iml.datetime()

AttributeError: module 'ibis_ml' has no attribute 'datetime'
```

There are my versions. 

```
ibis-framework==9.3.0
ibis-ml==0.1.2
```

**Comment by deepyaman** [comment]
Nice catch! IbisML has `date`, `time`, and `timestamp` selectors (as well as `temporal`), so you're probably looking for `timestamp`; `datetime` seems to be an oversight in the docs.
