### ISSUE TITLE
Broken link to `Recipes` on `README.md`

### ISSUE THREAD

**Issue by datajoely** [ibis-project/ibis-ml#143]
This [link](https://github.com/ibis-project/ibis-ml/blob/main/reference/core.html) no long exists. 

It's possible that [this notebook](https://github.com/ibis-project/ibis-ml/blob/main/reference/core.html#ibis_ml.Recipe) is the right replacement?

**Comment by deepyaman** [comment]
> This [link](https://github.com/ibis-project/ibis-ml/blob/main/reference/core.html) no long exists.
> 
> It's possible that [this notebook](https://github.com/ibis-project/ibis-ml/blob/main/reference/core.html#ibis_ml.Recipe) is the right replacement?

Hmm, it compiles to the right link on the website (https://ibis-project.github.io/ibis-ml/reference/core.html#ibis_ml.Recipe). Maybe it should just be a hardcoded link to the website instead of a relative reference?

If you want to raise a PR for it here and in the notebook, happy to accept. :)
