### ISSUE TITLE
feat: support conda install

### ISSUE THREAD

**Issue by jitingxu1** [ibis-project/ibis-ml#153]
Added support for conda install to make the package more accessible to users who prefer managing dependencies with Conda.

**Comment by jcrist** [comment]
Submitting a package to conda-forge is pretty straightforward: https://conda-forge.org/docs/maintainer/adding_pkgs/, let me know if you need any help.

**Comment by deepyaman** [comment]
IbisML is available on `conda-forge`: https://github.com/conda-forge/ibis-ml-feedstock
