### ISSUE TITLE
[EPIC] Launch IbisML

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis-ml#17]
**Acceptance criteria**: IbisML is improved and publicly launched with a blog. 

TODOs:

- [ ] investigate integration with https://github.com/ydataai/ydata-profiling

**Comment by gforsyth** [comment]
Can we define "release" for this?

**Comment by lostmygithubaccount** [comment]
true, let me just edit -- we've "released" but we haven't really launched in any public way, that's what this is to capture

**Comment by lostmygithubaccount** [comment]
**Weekly Update**:
2024-01-18

- no update

(copying over last week's update on behalf of Gil)

**Comment by gforsyth** [comment]
No update

**Comment by gforsyth** [comment]
* Meeting (2024/02/01) to discuss direction and planning for IbisML

**Comment by jcrist** [comment]
- Met to plan out user stories, sync on current status and design.

**Comment by jcrist** [comment]
**Weekly Update:**
2024-02-15

- Continued knowledge transfer to (former) claypot team.
- Continued research and planning out scope and design for a new redesigned ibisml  package.

**Comment by lostmygithubaccount** [comment]
**Weekly Update**: 
2024-02-22

- see https://github.com/ibis-project/ibisml/issues/19 for continued discussion
- Jim working on a refactor

**Comment by jcrist** [comment]
**Weekly Update:**
2024-03-07

- Refactor PR is up but not yet merged.

**Comment by jitingxu1** [comment]
**Weekly Update**:
2024-03-21

- data preprocessing transformation priority: https://github.com/ibis-project/ibisml/issues/32
- Create issues for P0 transformation 
- Create issues for other tasks: test coverage, code clean up

**Comment by jitingxu1** [comment]
**Weekly Update**
2024-03-29
PR in review
https://github.com/ibis-project/ibisml/pull/48
PR in progress
https://github.com/ibis-project/ibisml/issues/34

**Comment by jitingxu1** [comment]
**Weekly Update**

Demo is in progress

PR in review
 - https://github.com/ibis-project/ibisml/pull/48
 - #53 
 
PR in progress
 - https://github.com/ibis-project/ibisml/issues/34

**Comment by jitingxu1** [comment]
**Weekly Update**
2024-04-11
Demo
- Internal demo on 2024-4-11

ML Preprocessing steps implementation
- Merged
     - Zero-variance filter
- Review
   - Polynomial features(resolved feedbacks and wait for new review): https://github.com/ibis-project/ibisml/pull/53 
   - KBinsDiscretizer: https://github.com/ibis-project/ibisml/pull/57
- In Process
    - https://github.com/ibis-project/ibisml/issues/34
    - https://github.com/ibis-project/ibisml/issues/45

**Comment by jitingxu1** [comment]
**Weekly Update**
2024-04-18
Demo
- Did internal demo using duckdb on nycflights data, collected feedbacks for the incoming demo
- Booked the company tech demo on May 2nd. 

Backends: 
- Ran ML modeling use ibisml and sklearn on Theseus, it works but some steps have issue, will keep working on this

ML Preprocessing steps implementation (P0)
- Merged
    - Zero-variance filter
    - Polynomial features
- Review
    - KBinsDiscretizer: https://github.com/ibis-project/ibis-ml/pull/57
    - Outlier: https://github.com/ibis-project/ibis-ml/pull/68
- In Process
     - https://github.com/ibis-project/ibis-ml/issues/34
- todo
    - Ratio Variable generation [Will pause this one and Prioritize the demo work ]

**Comment by jitingxu1** [comment]
**Weekly Update**
2024-04-24
Demo
 - Run the same ml workflow on Theseus, detected some issues, and did some fix and raise the issues to the stakeholders.


Newly Merged PRs
- (feat)Outlier: https://github.com/ibis-project/ibis-ml/pull/68
-  (bug)Fix one hot encoding `nan` and cast Null to int issue

Review
- KBinsDiscretizer: https://github.com/ibis-project/ibis-ml/pull/57
- https://github.com/ibis-project/ibis-ml/issues/34

**Comment by jitingxu1** [comment]
**Weekly Update**
2024-05-02

Demo:
- Company Demo: Executing a machine learning workflow using scikit-learn with various models (scikit-learn, XGBoost, PyTorch) across different environments including Theseus, BigQuery, and DuckDB

Tech
- update ibis dependency to 9.0
- merged two new preprocessing steps: KbinsDiscretizer and target encoding
- add model picker to examples
- support torch 
- restructure ibisml website and add newly steps to documentation
- fixed bugs:

**Comment by jitingxu1** [comment]
**Weekly Update**
2024-05-15

We majorly focus on release work for the past two weeks, including planning, bug fix and codebase refactor.

Done:
- code refactor
    - rename it to ibis_ml
    - make moudules under step private
- make websites and docs prettier
-  bug-fix

In Progress
- Add support matrix for different backends
- Unit tests for different backends. [we may only use the support matrix to tell users how many steps are available for the specific backend, this effort probably will not continue]

**Comment by jitingxu1** [comment]
**Weekly Update**
2024-05-23

Done
- Submitted 30-min talk abstract to ODSC-West
- Initial version of ibisML support matrix - [link](https://docs.google.com/spreadsheets/d/1hu5blb0wsEyG_4a9JifThjw93NsriitjIr5Sj020eZ0/edit?usp=sharing), plan to better  show the information to the users, and prepare the [2024 table contest](https://posit.co/blog/announcing-the-2024-table-contest/)

In Progress
- #101 
- #100

**Comment by jitingxu1** [comment]
**Weekly Update**
2024-05-30

Done
- ibisML version 0.10 pypi [release](https://pypi.org/project/ibis-ml/)
- Better website
    - publish support [matrix](https://ibis-project.github.io/ibis-ml/support_matrix.html) 
    - Make the better tutorial: https://ibis-project.github.io/ibis-ml/tutorial/pytorch.html
    - How to build your own transformer #116 

Todo:
- blogpost
- Add the remains to FAQ in #92 #69

**Comment by jitingxu1** [comment]
**Weekly Update**
2024-06-28

Done
1. Improve rendering of support matrix
2. Q3 planning

In progress

1. kagge competition notebook example
3. train_test_split

Todo:

- Convert notebook to qmd for easier review and blogpost
- Add FAQ section to website [from last week]

**Comment by deepyaman** [comment]
Closing as IbisML 0.1.0 is already released, and we can more easily track/close out individual tasks as issues.
