### ISSUE TITLE
feat: Add ML operator support matrix, and ideally compares coverage with other major framework such as scikit-learn

### ISSUE THREAD

**Issue by zhenzhongxu** [ibis-project/ibis-ml#30]
It'll be nice to have an operator support matrix similar to [Ibis'](https://ibis-project.org/support_matrix), with coverages compare to 
[scikit-learn](https://scikit-learn.org/stable/modules/classes.html)

**Comment by deepyaman** [comment]
I think https://github.com/ibis-project/ibis-ml/issues/32 is sufficient for now.

> It'll be nice to have an operator support matrix similar to [Ibis'](https://ibis-project.org/support_matrix), with coverages compare to
[scikit-learn](https://scikit-learn.org/stable/modules/classes.html)

Specifically, Ibis measures coverage of each of it's own backends automatically (i.e. not coverage of operations supported by individual backends, such as whether something you can do in Postgres can be done in raw Ibis). Measuring coverage against scikit-learn will need to be maintained somewhat manually.

**Comment by jitingxu1** [comment]
https://github.com/ibis-project/ibis-ml/issues/32
https://github.com/ibis-project/ibis-ml/pull/102

done
