### ISSUE TITLE
Repr for `Recipe` and `Step`

### ISSUE THREAD

**Issue by jcrist** [ibis-project/ibis-ml#36]
We used to have nicer custom reprs for each `Step` and `Recipe`, but these were dropped in the refactor. Now that we're going for scikit-learn compatibility, it would be nice if our repr would match their conventions. We _could_ accomplish this by subclassing `Recipe` from `BaseEstimator`, but currently we don't have `sklearn` as a required dependency (since we want to support non-sklearn workflows as well too). My guess is there's a way we can have a repr that follows sklearn's conventions here without relying on sklearn itself for an implementation.

**Comment by deepyaman** [comment]
# Goal

How does sklearn represent subpipelines? We should basically use the same representation for a recipe.

```pycon
>>> from sklearn.feature_selection import SelectKBest
>>> from sklearn.pipeline import Pipeline
>>> from sklearn.svm import SVC
>>> import ibis_ml as ml
>>>
>>> imputer = ml.ImputeMean(ml.numeric())
>>> scaler = ml.ScaleStandard(ml.numeric())
>>> rec = ml.Recipe(imputer, scaler)
>>> pipe = Pipeline([("rec", rec), ("svc", SVC())])
>>> pipe
Pipeline(steps=[('rec', <ibis_ml.core.Recipe object at 0x164f28df0>),
                ('svc', SVC())])
>>> subpipe = Pipeline(steps=[('select', SelectKBest(k=2)), ("svc", SVC())])
>>> pipe = Pipeline([("rec", rec), ("sub", subpipe)])
>>> pipe
Pipeline(steps=[('rec', <ibis_ml.core.Recipe object at 0x164f28df0>),
                ('sub',
                 Pipeline(steps=[('select', SelectKBest(k=2)),
                                 ('svc', SVC())]))])
```

Considerations:

* We will probably need to give steps a name.
* `_EstimatorPrettyPrinter` _IS NOT_ straightforward: https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/utils/_pprint.py#L116
