### ISSUE TITLE
chore: rename IbisML/`ibisml` to Ibis-ML/`ibis-ml`

### ISSUE THREAD

**Issue by deepyaman** [ibis-project/ibis-ml#38]
Rename the library ahead of release, to avoid autocorrecting to/mispronunciation as "abysmal." 😂 

Will require removing the existing package, as the package name `ibis-ml` is too similar to the existing one to be published on PyPI.

**Comment by lostmygithubaccount** [comment]
can it be IbisML/`ibis-ml`? something about Ibis-ML irks me...

(this is not important tho)

**Comment by deepyaman** [comment]
> can it be IbisML/`ibis-ml`? something about Ibis-ML ~irks me~ is abysmal to me...
> 
> (this is not important tho)

Sure; I care more about the package name, you can have your 🐫. :)

**Comment by gforsyth** [comment]
`pip` is case-insensitive, so I don't know that IbisML will avoid the abysmal reading

**Comment by lostmygithubaccount** [comment]
I just mean in prose calling it "IbisML" instead of "Ibis-ML", the pip package being `ibis-ml` makes sense
