### ISSUE TITLE
docs: build demo workflows

### ISSUE THREAD

**Issue by jitingxu1** [ibis-project/ibis-ml#49]
~We are currently targeting the [NVTabular demo on RecSys2020 Challenge](https://nvidia-merlin.github.io/NVTabular/main/examples/winning-solution-recsys2020-twitter/01-02-04-Download-Convert-ETL-with-NVTabular-Training-with-XGBoost.html) as a demo workflow.~ **Update:** Due to the RecSys2020 demo data being unavailable (and against Twitter's terms to share), we will start with the R `nycflights13` dataset. [It has been added to Ibis examples to support this.](https://github.com/ibis-project/ibis/pull/8746)

### Major tasks

1. Demo Dataset
    - nycflights13
1. Feature engineering
    - Use ibis and ibisml for data preprocessing 
1. Model training
    - XGBoost
    - sklearn
    - PyTorch

**Comment by deepyaman** [comment]
Initial version merged in #60. Some remaining TODOs:

* Make sure unique key is actually unique
* Do we want to do something with weather data? We join it, and then throw away all the columns...
* Include `TargetEncoding` step
* Clearly document handoff to other modeling frameworks (did test `XGBClassifier` works, but add it to a notebook; also, make sure PyTorch demo is there)... (maybe add model choice to demo notebook)

**Comment by deepyaman** [comment]
> Initial version merged in #60. Some remaining TODOs:
> 
> * [ ]  Make sure unique key is actually unique
> * [ ]  Do we want to do something with weather data? We join it, and then throw away all the columns...
> * [x]  Include `TargetEncoding` step
> * [x]  Clearly document handoff to other modeling frameworks (did test `XGBClassifier` works, but add it to a notebook; also, make sure PyTorch demo is there, maybe something like `skorch` with MLP)... (maybe add model choice to demo notebook)
> * [x]  Once Ibis 9.0 is released, update demo notebook to pull directly from `ibis.examples.nycflights13_*.fetch()` instead of local DuckDB

The remaining TODOs don't seem like a pressing priority; will close this as completed.
