### ISSUE TITLE
docs: add missing steps to documentation

### ISSUE THREAD

**Issue by jitingxu1** [ibis-project/ibis-ml#51]
The recently-added steps are not rendering on https://ibis-project.github.io/ibis-ml/. This task should add all the missing steps to the docs; from here forward, we should ideally make sure PRs that add new steps also add them to the docs.

(Maybe also confirm whether https://github.com/ibis-project/ibis-ml/blob/main/docs/_quarto.yml needs to be updated on each PR, or if this could be better handled by the API doc generation.)

**Comment by jcrist** [comment]
Can you be more specific about what's needed here? We already have (limited) documentation (mostly API docs) in https://github.com/ibis-project/ibisml/tree/main/docs, rendered [here](https://ibis-project.github.io/ibisml/).

**Comment by jitingxu1** [comment]
> Can you be more specific about what's needed here? We already have (limited) documentation (mostly API docs) in https://github.com/ibis-project/ibisml/tree/main/docs, rendered [here](https://ibis-project.github.io/ibisml/).

I will update the title, add new steps to the documentation, and include them in the API reference. I am unsure whether these changes are automatically detected or if human involvement is required.
