### ISSUE TITLE
doc: change ImputeMode for categorical features

### ISSUE THREAD

**Issue by jitingxu1** [ibis-project/ibis-ml#58]
ImputeMode should be recommended for categorical features.

It is use numeric column in the example. 

<img width="1017" alt="image" src="https://github.com/ibis-project/ibisml/assets/126802425/8a9dc8d8-b3fb-4849-b9cb-9784c60ca0f8">

**Comment by deepyaman** [comment]
Doesn't matter too much to me personally. However, fine with changing this if we verify `ImputeMode`/Ibis `.mode()` works on non-numeric columns.
