### ISSUE TITLE
docs(website): explain how users can perform train-test splitting with Ibis

### ISSUE THREAD

**Issue by jitingxu1** [ibis-project/ibis-ml#62]
randomly partition a dataset into subsets while ensuring reproducibility

Reference:
- https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
- https://rsample.tidymodels.org/reference/initial_split.html

**Comment by deepyaman** [comment]
https://github.com/ibis-project/ibis-ml/pull/60 implements a basic (approximate) train-test split using Ibis. It could be very nice to wrap this up as part of a utility in IbisML, but it would be the only non-`Step` utility at this time. Maybe it's sufficient to just show it in the demo notebook for now? I'm not sure.

**Comment by lostmygithubaccount** [comment]
demonstrating how it's done w/ sufficient explanation seems fine for now

**Comment by deepyaman** [comment]
> demonstrating how it's done w/ sufficient explanation seems fine for now

Updated the issue title to reflect this.

**Comment by deepyaman** [comment]
Explanation is in the tutorial; @jitingxu1 created https://github.com/ibis-project/ibis-ml/pull/124 with an implementation, so let's close this as completed.
