### ISSUE TITLE
feat: Run ml data preprocess workflow on different backends[Theseus and big query]

### ISSUE THREAD

**Issue by jitingxu1** [ibis-project/ibis-ml#64]
Run ml data preprocess workflow on different backends[Theseus and big query].

It may involves the following tasks:

1. spinup Backend engine
2. Larger size dataset
    - Fannie mae SFH Mortgage could be one choice
    - Credit card Fraud detection
4. Build the preprocessing pipeline

**Comment by deepyaman** [comment]
> 2. Larger size dataset
>    
>    * Fannie mae SFH Mortgage could be one choice
>    * Credit card Fraud detection

For our initial demo (e.g. on Theseus), it should be OK to show that IbisML can execute on additional backends, without using a larger dataset (we already know the backend should scale).

In the future, it would definitely be nice to be able to demonstrate something like Theseus on a very large dataset; perhaps, by that time, we could even curate a large flight dataset (or add additional demos as suggested above).

**Comment by jitingxu1** [comment]
done at the demo day
