### ISSUE TITLE
bug(bigquery): invalid field name Cast(y, int64) in bigquery

### ISSUE THREAD

**Issue by jitingxu1** [ibis-project/ibis-ml#93]
See [this ibis issue](https://github.com/ibis-project/ibis/issues/9112) for details.
I'm not 100% if this will get other errors, but one potential fix is to remove the `ibis.memtable()` [here](https://github.com/ibis-project/ibis-ml/blob/main/ibis_ml/steps/encode.py#L352), I do see we have other places uses `memtable`, need to double check and test the usage of `memtable` in other place.

To reproduce the error in ibis-ml:

```python
import ibis
con = ibis.bigquery.connect(project_id="xxx", dataset_id="xxx")
t = ibis.memtable({
    "x": ["a", "b"],
    "y": ["0", "1"]
})
con.create_table(
    "t", t.to_pyarrow(), overwrite=True
)

t = con.table("t")
t = t.mutate(
    x1=ibis.literal("c"),
    y=_.y.cast("int32"),
)

x = t.drop("y")
y = t.y.cast("int64")

import ibis_ml as ml

step = ml.TargetEncode(["x"])
table, targets, index = ml.core.normalize_table(x, y)
print(targets)
metadata = ml.core.Metadata(targets=targets)
step.fit_table(table,metadata)
step.transform_table(x)
```

error:
```
BadRequest: 400 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/voltrondata-demo/jobs?uploadType=multipart:
 Invalid field name "Cast(y, int64)_194474".
 Fields must contain the allowed characters, 
and be at most 300 characters long. 
For allowed characters, please refer to https://cloud.google.com/bigquery/docs/schemas#column_names
```

**Comment by deepyaman** [comment]
> I'm not 100% if this will get other errors, but one potential fix is to remove the `ibis.memtable()` [here](https://github.com/ibis-project/ibis-ml/blob/d629901/ibis_ml/steps/_encode.py#L352)

This won't do anything, because https://github.com/ibis-project/ibis/blob/77d6cb620238b8f6e18f5aa940edf8017652d37c/ibis/expr/types/joins.py#L236 will cast it right to a `memtable` again.

Closing this, as the user can easily get around the issue outside of the step use. We could consider some opinionated column name sanitization in the future, but that may not be desirable on all backends.
